GENRE_MAPPER = {
    "role-playing": ("rpg", 1),
    "action rpg": ("rpg", 1),
    "console-style rpg": ("rpg", 1),
    "japanese-style": ("rpg", 1),
    "pc-style rpg": ("rpg", 1),
    "western-style": ("rpg", 1),
    "action": ("action", 2),
    "action adventure": ("action", 2),
    "beat-'em-up": ("action", 2),
    "open-world": ("action", 2),
    "survival": ("action", 2),
    "shooter": ("shooter", 3),
    "first-person": ("shooter", 3),
    "third-person": ("shooter", 3),
    "light gun": ("shooter", 3),
    "shoot-'em-up": ("shooter", 3),
    "adventure": ("adventure", 4),
    "point-and-click": ("adventure", 4),
    "visual novel": ("adventure", 4),
    "hidden object": ("adventure", 4),
    "text": ("adventure", 4),
    "strategy": ("strategy", 5),
    "tactics": ("strategy", 5),
    "tactical": ("strategy", 5),
    "turn-based": ("strategy", 5),
    "real-time": ("strategy", 5),
    "4x": ("strategy", 5),
    "wargame": ("strategy", 5),
    "city building": ("strategy", 5),
    "management": ("strategy", 5),
    "business / tycoon": ("strategy", 5),
    "tycoon": ("strategy", 5),
    "defense": ("strategy", 5),
    "simulation": ("simulation", 6),
    "sim": ("simulation", 6),
    "flight": ("simulation", 6),
    "driving": ("simulation", 6),
    "sandbox": ("simulation", 6),
    "virtual life": ("simulation", 6),
    "breeding/constructing": ("simulation", 6),
    "trainer": ("simulation", 6),
    "exercise / fitness": ("simulation", 6),
    "sports": ("sports", 7),
    "soccer": ("sports", 7),
    "football": ("sports", 7),
    "basketball": ("sports", 7),
    "tennis": ("sports", 7),
    "golf": ("sports", 7),
    "baseball": ("sports", 7),
    "ice hockey": ("sports", 7),
    "cricket": ("sports", 7),
    "boxing": ("sports", 7),
    "boxing / martial arts": ("sports", 7),
    "wrestling": ("sports", 7),
    "skateboarding": ("sports", 7),
    "skate / skateboard": ("sports", 7),
    "skiing": ("sports", 7),
    "ski / snowboard": ("sports", 7),
    "snowboarding": ("sports", 7),
    "surfing": ("sports", 7),
    "fishing": ("sports", 7),
    "olympic sports": ("sports", 7),
    "athletics": ("sports", 7),
    "volleyball": ("sports", 7),
    "racing": ("racing", 8),
    "kart": ("racing", 8),
    "formula one": ("racing", 8),
    "stock car": ("racing", 8),
    "rally / offroad": ("racing", 8),
    "gt / street": ("racing", 8),
    "motocross": ("racing", 8),
    "puzzle": ("puzzle", 9),
    "logic": ("puzzle", 9),
    "matching": ("puzzle", 9),
    "stacking": ("puzzle", 9),
    "fighting": ("fighting", 10),
    "platformer": ("platformer", 11),
    "music": ("music", 12),
    "rhythm": ("music", 12),
    "dancing": ("music", 12),
    "music maker": ("music", 12),
    "party": ("party", 13),
    "party / minigame": ("party", 13),
    "trivia / game show": ("party", 13),
    "board games": ("board_game", 14),
    "board / card game": ("board_game", 14),
    "card battle": ("board_game", 14),
    "billiards": ("board_game", 14),
    "gambling": ("board_game", 14),
    "parlor": ("board_game", 14),
    "massively multiplayer": ("mmo", 15),
    "massively multiplayer online": ("mmo", 15),
    "moba": ("mmo", 15),
    "arcade": ("arcade", 16),
    "pinball": ("arcade", 16),
    "horror": ("horror", 17),
    "general": ("unknown", 999),
    "miscellaneous": ("unknown", 999),
    "other": ("unknown", 999),
    "": ("unknown", 999),
}

PLATFORM_CATEGORY_PATHS = {
    "3ds": "nintendo/3ds",
    "dreamcast": "dreamcast",
    "ds": "nintendo/ds",
    "game-boy-advance": "nintendo/game-boy-advance",
    "game boy advance": "nintendo/game-boy-advance",
    "gamecube": "nintendo/gamecube",
    "nintendo": "nintendo",
    "nintendo 3ds": "nintendo/3ds",
    "nintendo ds": "nintendo/ds",
    "nintendo game boy advance": "nintendo/game-boy-advance",
    "nintendo gamecube": "nintendo/gamecube",
    "nintendo-64": "nintendo/nintendo-64",
    "nintendo switch": "nintendo/switch",
    "pc": "pc",
    "playstation": "playstation-platform",
    "playstation-1": "playstation-platform/playstation-1",
    "playstation 2": "playstation-platform/ps2",
    "playstation-2": "playstation-platform/playstation-2",
    "playstation 3": "playstation-platform/ps3",
    "playstation-3": "playstation-platform/playstation-3",
    "playstation 4": "playstation-platform/ps4",
    "playstation-4": "playstation-platform/playstation-4",
    "playstation 5": "playstation-platform/ps5",
    "playstation-5": "playstation-platform/playstation-5",
    "playstation portable": "playstation-platform/psp",
    "playstation-vita": "playstation-platform/playstation-vita",
    "ps2": "playstation-platform/ps2",
    "ps3": "playstation-platform/ps3",
    "ps4": "playstation-platform/ps4",
    "ps5": "playstation-platform/ps5",
    "psp": "playstation-platform/psp",
    "stadia": "stadia",
    "switch": "nintendo/switch",
    "wii": "nintendo/wii",
    "wii u": "nintendo/wii-u",
    "wii-u": "nintendo/wii-u",
    "xbox": "xbox-platform",
    "xbox-360": "xbox-platform/xbox-360",
    "xbox 360": "xbox-platform/xbox-360",
    "xbox-one": "xbox-platform/xbox-one",
    "xbox one": "xbox-platform/xbox-one",
    "xbox-series-x": "xbox-platform/xbox-series-x",
    "xbox series x": "xbox-platform/xbox-series-x",
}

REGEX_ALPHANUM = r"[^a-zA-Z0-9]+"
